services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ThinkDigital\ContaoTheLightbox\:
        resource: '../../*'
        exclude:
            - '../../ContaoManager/'
            - '../../DependencyInjection/'
            - '../../ContaoTheLightboxBundle.php'
